title = "Kube-o-Matic"

[app]
version="v1alpha1"
language="go"
name = "kube-o-matic"
description = "a tool to deploy services to k8s cloud or in-house and monitor/control kubernetes"
github_URL = "github.com/miladhzzz/kube-o-matic"
owner="milad hosseini"

[app.services]
port = "8555"

[app.build]
build = "yes"

[app.test]
test = "go.test"

[app.deploy]
deploy = "yes"
namespace = "cicd"
replica= "3"
monitor= "yes"

[dependencis]
